### ISSUE TITLE
Single HTML file

### ISSUE THREAD

**Issue by Fastidious** [ronaegis/aeschat#2]
The "About" reads:
- Single HTML file, source at GitHub, view source.

That gives the impression that it is a plain HTML/JS solution, yet, this is a Node application, and will not work without Node. Am I correct, or am I missing something?

**Comment by ronaegis** [comment]
Oh you are right. That is a leftover from when the project was initially started. This is not true anymore, with all the other dependencies.

I removed it (along with other minor updates) in 1e34dee95e434161b9cf6ed1588e6ac4ea01615d
